language: php

php:
  - 5.4
  - 5.5
#  - 5.6
#  - 7.0
#  - 7.1
#  - 7.2

env:
  - SPHINX_VERSION=2

# run build against hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:
    - env: SPHINX_VERSION=3
  include:
    - php: 5.4
      env: SPHINX_VERSION=3

services:
  - mysql

sudo: true

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  # show some versions and env information
  - mysql --version

  # initialize databases
  - travis_retry mysql -e 'CREATE DATABASE `yiitest`;';
  - tests/data/travis/sphinx-setup.sh
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi
  - composer require --prefer-dist --no-interaction 'phpunit/phpunit:4.8.27|~5.7.21|^6.2'

script:
  - vendor/bin/phpunit --verbose $PHPUNIT_FLAGS

after_script:
  - cat sphinx/searchd.log
  - cat sphinx/query.log